apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-data
data:
  default.yaml: |-
    apiVersion: 1

    datasources:
      - name: Prometheus
        type: prometheus
        editable: true
        is_default: true
        access: proxy
        url: http://prometheus:9090

