apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-cm
data:
  prometheus.yml: |-
    global:
      scrape_interval: 3s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
        - targets: ['prometheus:9090']
    scrape_configs:
      - job_name: 'example'
        static_configs:
        - targets: ['app:5000']
